# case_data_schema.yaml
case_data:
  description: "Complete state of a client's case and interview including all pertinent details and conversation history"
  case_number: 
    type: string
    description: "Unique identifier for the case"
  intake_date:
    type: date
    description: "Date when the case intake was started"
  status:
    type: string 
    description: "Current status of the case"
    default: "intake_in_progress"

  personal_info:
    description: "Personal information of the client including name, age, gender, date of birth, home address, email, and phone number"
    first_name:
      type: string
      description: "First name of the client"
      examples: ["John", "Jane"]
    last_name:
      type: string 
      description: "Last name of the client"
      examples: ["Doe", "Smith"]
    age:
      type: integer
      description: "Age of the client"
      examples: [30, 25]
    gender:
      type: string
      description: "Gender of the client" 
      examples: ["Male", "Female"]
    date_of_birth:
      type: date
      description: "Date of birth of the client"
      examples: ["1990-01-01", "1985-05-15"]
    home_address:
      type: string
      description: "Home address of the client"
      examples: ["123 Main St, Anytown, USA", "456 Elm St, Othertown, USA"]
    email:
      type: string
      description: "Email of the client"
      examples: ["john.doe@example.com", "jane.smith@example.com"]
    phone:
      type: string
      description: "Phone number of the client"
      examples: ["1234567890", "0987654321"]
    preferred_contact_method:
      type: string?
      description: "Preferred contact method of the client"
      examples: ["email", "phone"]

  incident_details:
    description: "Details about the incident including time, date, location, and description"
    incident_date:
      type: datetime
      description: "Time and date of the incident"
      examples: ["2024-01-01 10:00:00", "2024-02-01 14:30:00"]
    incident_time:
      type: string
      description: "Time of day of the incident"
      examples: ["morning", "afternoon", "evening", "night"]
    incident_location:
      type: string
      description: "Location of the incident"
      examples: ["123 Main St, Anytown, USA", "456 Elm St, Othertown, USA"]
    incident_description:
      type: string
      description: "Description of the incident"
      examples: ["I was walking down the street and a car hit me", "I was at work and a machine malfunctioned and injured me"]
    incident_type:
      type: string
      description: "Type of the incident"
      examples: ["workplace", "car accident", "slip and fall", "medical malpractice", "product liability", "other"]

  witness_info:
    description: "Information about any witnesses to the incident including their contact details and statement"
    name:
      type: string?
      description: "Witness's full name if provided"
      examples: ["John Smith", "Mary Wilson"]
    contact_info:
      type: string?
      description: "Witness's contact information if provided"
      examples: ["(555) 123-4567", "john.smith@email.com"]
    relationship:
      type: string?
      description: "Witness's relationship to the client if provided"
      examples: ["Friend", "Coworker", "Neighbor"]
    statement:
      type: string?
      description: "Witness's statement if provided"
      examples: ["I saw the accident happen", "I was with the client when it happened"]

  injury_details:
    description: "Details about the injury including symptoms, severity, duration, and impact"
    list_injury_details:
      type: [string]
      description: "List of all injuries"
      examples: ["I have a sprained ankle", "I have a broken arm", "I have a concussion"]
    symptom_details:
      type: [string]
      description: "Details about each symptom"
      examples: ["I have pain in my ankle", "I have swelling in my arm", "I have dizziness"]
    injury_severity:
      type: string
      description: "Severity of the injury"
      examples: ["minor", "moderate", "severe"]
    injury_duration:
      type: string
      description: "Duration of the injury"
      examples: ["I have had this injury for 2 days", "I have had this injury for 2 weeks"]
    injury_impact:
      type: string
      description: "Impact of the injury"
      examples: ["I am unable to work", "I am unable to walk", "I am unable to move my arm"]

  medical_info:
    description: "Medical treatment history including facilities, doctors, and current/future treatment plans"
    initial_treatment:
      type: string
      description: "Initial medical treatment received"
      examples: ["Went to ER", "Saw primary care doctor next day"]
    treatment_facilities:
      type: [string]
      description: "Medical facilities visited"
      examples: ["Memorial Hospital", "City Medical Center"]
    treating_physicians:
      type: [string]
      description: "Names of treating doctors"
      examples: ["Dr. Smith", "Dr. Jones"]
    current_treatment:
      type: string
      description: "Current treatment status"
      examples: ["Physical therapy 2x/week", "No current treatment"]
    future_treatment_needed:
      type: string?
      description: "Planned future treatment"
      examples: ["Surgery scheduled", "Ongoing physical therapy needed"]
    pre_existing_conditions:
      type: string?
      description: "Extract relevant pre-existing conditions"
      examples: ["Prior back injury", "No pre-existing conditions"]
    medications:
      type: [string]?
      description: "Medications prescribed"
      examples: ["Ibuprofen", "Muscle relaxers"]

  insurance_info:
    description: "Insurance information including policy number, provider, and coverage details"
    client_insurance:
      description: "Insurance policy information"
      company_name:
        type: string
        description: "Insurance company name"
        examples: ["Blue Cross Blue Shield", "United Healthcare"]
      policy_number:
        type: string
        description: "Insurance policy number"
        examples: ["1234567890", "0987654321"]
      policy_holder_name:
        type: string
        description: "Name of the policy holder"
        examples: ["John Doe", "Jane Smith"]
      coverage_details:
        type: string
        description: "Coverage details"
        examples: ["$100,000 per accident", "50% coverage for medical expenses"]
      policy_start_date:
        type: date
        description: "Date when the policy was started"
        examples: ["2024-01-01", "2024-02-01"]
      policy_end_date:
        type: date
        description: "Date when the policy was ended"
        examples: ["2024-01-01", "2024-02-01"]
      policy_type:
        type: string
        description: "Type of the policy"
        examples: ["Health", "Life", "Auto", "Home", "Other"]
      policy_status:
        type: string
        description: "Status of the policy"
        examples: ["Active", "Inactive", "Pending", "Other"]
    insurance_notified:
      type: boolean
      description: "Whether the insurance company has been notified"
    notification_date:
      type: date?
      description: "Date when the insurance company was notified"
      examples: ["2024-01-01", "2024-02-01"]
    claim_number:
      type: string?
      description: "Insurance claim number"
      examples: ["1234567890", "0987654321"]
    claim_status:
      type: string?
      description: "Status of the claim"
      examples: ["Pending", "In Progress", "Closed"]

  employment_info:
    description: "Employment information including employer, position, and employment details"
    current_employer:
      description: "Current employer information"
      company_name:
        type: string
        description: "Employer"
        examples: ["Acme Inc.", "XYZ Corp."]
      address:
        type: string
        description: "Address of the employer"
        examples: ["123 Main St, Anytown, USA", "456 Elm St, Othertown, USA"]
      phone:
        type: string
        description: "Phone number of the employer"
        examples: ["(555) 123-4567", "123-456-7890"]
    employment_status_at_incident:
      type: string
      description: "Employment status at the time of the incident"
      examples: ["Employed", "Unemployed", "Retired", "Student", "Other"]
    employment_type:
      type: string
      description: "Employment type"
      examples: ["Full-time", "Part-time", "Temporary"]
    position:
      type: string
      description: "Position"
      examples: ["Software Engineer", "Sales Associate"]
    work_missed:
      type: string
      description: "Whether the client missed work due to the injury"
    income_loss:
      type: string
      description: "Whether the client has experienced a loss of income due to the injury"
    work_restrictions:
      type: string
      description: "Whether the client has restrictions on their work due to the injury"
      examples: ["unable to work", "able to work but with limitations like lifting", "other"]

  damages_info:
    description: "Financial impact of the incident including medical costs, property damage and lost wages"
    medical_expenses:
      type: float?
      description: "Total medical expenses incurred"
      examples: [5000.00, 12500.50]
    property_damage:
      type: float?
      description: "Total property damage costs"
      examples: [2000.00, 15000.00]
    lost_wages:
      type: float?
      description: "Total lost wages amount"
      examples: [3000.00, 8000.00]
    other_expenses:
      type: {string: float}?
      description: "Any other expenses with descriptions"
      examples: {"Transportation": 500.00, "Home care": 1200.00}
    future_expenses:
      type: string?
      description: "Anticipated future expenses"
      examples: ["Ongoing physical therapy estimated at $200/week", "Future surgery estimated at $25,000"]

  legal_info:
    description: "Legal aspects of the case including prior representation, documents and settlement information"
    prior_attorneys:
      type: string?
      description: "Information about any previous attorneys consulted"
      examples: ["Consulted with Smith & Jones but didn't retain", "None"]
    signed_documents:
      type: string?
      description: "Details about legal documents already signed"
      examples: ["Signed medical release forms", "Insurance statement on 2024-01-15"]
    legal_deadlines:
      type: string?
      description: "Relevant legal deadlines or statutes of limitations"
      examples: ["Statute of limitations expires 2025-06-01", "Insurance claim deadline in 30 days"]
    settlement_offers:
      type: string?
      description: "Information about any settlement offers received"
      examples: ["Initial offer of $25,000 received on 2024-02-01", "No offers yet"]
    desired_outcome:
      type: string?
      description: "Client's desired outcome or settlement expectations"
      examples: ["Seeking compensation for all medical bills plus lost wages", "Fair settlement to cover future treatment"]